/**
 * Finance 国家/地区初始化数据。
 *
 * code 使用不含“+”前缀的国际电话区号，例如中国为 86。
 * MCC 按 ITU-T E.212 国家或地区分配维护。大多数国家只有一个 MCC；对于存在多个 MCC 的国家，
 * 选择当前最大移动运营商实际使用的代表 MCC。该字段用于业务报价检索，不表示该国家只有这一个 MCC。
 */
export const FINANCE_COUNTRY_DATA = [
    { code: '54', mcc: '722', cnName: '阿根廷', enName: 'Argentina' },
    { code: '55', mcc: '724', cnName: '巴西', enName: 'Brazil' },
    { code: '56', mcc: '730', cnName: '智利', enName: 'Chile' },
    { code: '57', mcc: '732', cnName: '哥伦比亚', enName: 'Colombia' },
    { code: '20', mcc: '602', cnName: '埃及', enName: 'Egypt' },
    { code: '33', mcc: '208', cnName: '法国', enName: 'France' },
    { code: '49', mcc: '262', cnName: '德国', enName: 'Germany' },
    { code: '852', mcc: '454', cnName: '香港', enName: 'Hong Kong' },
    { code: '36', mcc: '216', cnName: '匈牙利', enName: 'Hungary' },
    { code: '91', mcc: '405', cnName: '印度', enName: 'India' },
    { code: '62', mcc: '510', cnName: '印度尼西亚', enName: 'Indonesia' },
    { code: '972', mcc: '425', cnName: '以色列', enName: 'Israel' },
    { code: '39', mcc: '222', cnName: '意大利', enName: 'Italy' },
    { code: '60', mcc: '502', cnName: '马来西亚', enName: 'Malaysia' },
    { code: '52', mcc: '334', cnName: '墨西哥', enName: 'Mexico' },
    { code: '31', mcc: '204', cnName: '荷兰', enName: 'Netherlands' },
    { code: '234', mcc: '621', cnName: '尼日利亚', enName: 'Nigeria' },
    { code: '92', mcc: '410', cnName: '巴基斯坦', enName: 'Pakistan' },
    { code: '51', mcc: '716', cnName: '秘鲁', enName: 'Peru' },
    { code: '48', mcc: '260', cnName: '波兰', enName: 'Poland' },
    { code: '974', mcc: '427', cnName: '卡塔尔', enName: 'Qatar' },
    { code: '40', mcc: '226', cnName: '罗马尼亚', enName: 'Romania' },
    { code: '7', mcc: '250', cnName: '俄罗斯', enName: 'Russia' },
    { code: '966', mcc: '420', cnName: '沙特阿拉伯', enName: 'Saudi Arabia' },
    { code: '65', mcc: '525', cnName: '新加坡', enName: 'Singapore' },
    { code: '27', mcc: '655', cnName: '南非', enName: 'South Africa' },
    { code: '34', mcc: '214', cnName: '西班牙', enName: 'Spain' },
    { code: '90', mcc: '286', cnName: '土耳其', enName: 'Turkey' },
    { code: '971', mcc: '424', cnName: '阿拉伯联合酋长国', enName: 'United Arab Emirates' },
    { code: '44', mcc: '234', cnName: '英国', enName: 'United Kingdom' },
    { code: '1', mcc: '302', cnName: '加拿大', enName: 'Canada' },
    { code: '1', mcc: '311', cnName: '美国', enName: 'United States' },
    { code: '213', mcc: '603', cnName: '阿尔及利亚', enName: 'Algeria' },
    { code: '244', mcc: '631', cnName: '安哥拉', enName: 'Angola' },
    { code: '229', mcc: '616', cnName: '贝宁', enName: 'Benin' },
    { code: '267', mcc: '652', cnName: '博茨瓦纳', enName: 'Botswana' },
    { code: '226', mcc: '613', cnName: '布基纳法索', enName: 'Burkina Faso' },
    { code: '257', mcc: '642', cnName: '布隆迪', enName: 'Burundi' },
    { code: '237', mcc: '624', cnName: '喀麦隆', enName: 'Cameroon' },
    { code: '235', mcc: '622', cnName: '乍得', enName: 'Chad' },
    { code: '242', mcc: '629', cnName: '刚果共和国（布拉柴维尔）', enName: 'Republic of the Congo (Brazzaville)' },
    { code: '291', mcc: '657', cnName: '厄立特里亚', enName: 'Eritrea' },
    { code: '251', mcc: '636', cnName: '埃塞俄比亚', enName: 'Ethiopia' },
    { code: '241', mcc: '628', cnName: '加蓬', enName: 'Gabon' },
    { code: '220', mcc: '607', cnName: '冈比亚', enName: 'Gambia' },
    { code: '233', mcc: '620', cnName: '加纳', enName: 'Ghana' },
    { code: '245', mcc: '632', cnName: '几内亚比绍', enName: 'Guinea-Bissau' },
    { code: '225', mcc: '612', cnName: '科特迪瓦', enName: 'Ivory Coast' },
    { code: '254', mcc: '639', cnName: '肯尼亚', enName: 'Kenya' },
    { code: '266', mcc: '651', cnName: '莱索托', enName: 'Lesotho' },
    { code: '231', mcc: '618', cnName: '利比里亚', enName: 'Liberia' },
    { code: '218', mcc: '606', cnName: '利比亚', enName: 'Libya' },
    { code: '261', mcc: '646', cnName: '马达加斯加', enName: 'Madagascar' },
    { code: '265', mcc: '650', cnName: '马拉维', enName: 'Malawi' },
    { code: '223', mcc: '610', cnName: '马里', enName: 'Mali' },
    { code: '222', mcc: '609', cnName: '毛里塔尼亚', enName: 'Mauritania' },
    { code: '212', mcc: '604', cnName: '摩洛哥', enName: 'Morocco' },
    { code: '258', mcc: '643', cnName: '莫桑比克', enName: 'Mozambique' },
    { code: '264', mcc: '649', cnName: '纳米比亚', enName: 'Namibia' },
    { code: '227', mcc: '614', cnName: '尼日尔', enName: 'Niger' },
    { code: '250', mcc: '635', cnName: '卢旺达', enName: 'Rwanda' },
    { code: '221', mcc: '608', cnName: '塞内加尔', enName: 'Senegal' },
    { code: '232', mcc: '619', cnName: '塞拉利昂', enName: 'Sierra Leone' },
    { code: '252', mcc: '637', cnName: '索马里', enName: 'Somalia' },
    { code: '211', mcc: '659', cnName: '南苏丹', enName: 'South Sudan' },
    { code: '249', mcc: '634', cnName: '苏丹', enName: 'Sudan' },
    { code: '268', mcc: '653', cnName: '斯威士兰', enName: 'Swaziland' },
    { code: '255', mcc: '640', cnName: '坦桑尼亚', enName: 'Tanzania' },
    { code: '228', mcc: '615', cnName: '多哥', enName: 'Togo' },
    { code: '216', mcc: '605', cnName: '突尼斯', enName: 'Tunisia' },
    { code: '256', mcc: '641', cnName: '乌干达', enName: 'Uganda' },
    { code: '260', mcc: '645', cnName: '赞比亚', enName: 'Zambia' },
    { code: '263', mcc: '648', cnName: '津巴布韦', enName: 'Zimbabwe' },
    { code: '93', mcc: '412', cnName: '阿富汗', enName: 'Afghanistan' },
    { code: '61', mcc: '505', cnName: '澳大利亚', enName: 'Australia' },
    { code: '880', mcc: '470', cnName: '孟加拉国', enName: 'Bangladesh' },
    { code: '855', mcc: '456', cnName: '柬埔寨', enName: 'Cambodia' },
    { code: '86', mcc: '460', cnName: '中国', enName: 'China' },
    { code: '81', mcc: '440', cnName: '日本', enName: 'Japan' },
    { code: '856', mcc: '457', cnName: '老挝', enName: 'Laos' },
    { code: '976', mcc: '428', cnName: '蒙古', enName: 'Mongolia' },
    { code: '977', mcc: '429', cnName: '尼泊尔', enName: 'Nepal' },
    { code: '64', mcc: '530', cnName: '新西兰', enName: 'New Zealand' },
    { code: '675', mcc: '537', cnName: '巴布亚新几内亚', enName: 'Papua New Guinea' },
    { code: '63', mcc: '515', cnName: '菲律宾', enName: 'Philippines' },
    { code: '94', mcc: '413', cnName: '斯里兰卡', enName: 'Sri Lanka' },
    { code: '886', mcc: '466', cnName: '台湾', enName: 'Taiwan' },
    { code: '992', mcc: '436', cnName: '塔吉克斯坦', enName: 'Tajikistan' },
    { code: '66', mcc: '520', cnName: '泰国', enName: 'Thailand' },
    { code: '993', mcc: '438', cnName: '土库曼斯坦', enName: 'Turkmenistan' },
    { code: '998', mcc: '434', cnName: '乌兹别克斯坦', enName: 'Uzbekistan' },
    { code: '84', mcc: '452', cnName: '越南', enName: 'Vietnam' },
    { code: '355', mcc: '276', cnName: '阿尔巴尼亚', enName: 'Albania' },
    { code: '374', mcc: '283', cnName: '亚美尼亚', enName: 'Armenia' },
    { code: '994', mcc: '400', cnName: '阿塞拜疆', enName: 'Azerbaijan' },
    { code: '375', mcc: '257', cnName: '白俄罗斯', enName: 'Belarus' },
    { code: '359', mcc: '284', cnName: '保加利亚', enName: 'Bulgaria' },
    { code: '385', mcc: '219', cnName: '克罗地亚', enName: 'Croatia' },
    { code: '420', mcc: '230', cnName: '捷克共和国', enName: 'Czech Republic' },
    { code: '995', mcc: '282', cnName: '格鲁吉亚', enName: 'Georgia' },
    { code: '30', mcc: '202', cnName: '希腊', enName: 'Greece' },
    { code: '371', mcc: '247', cnName: '拉脱维亚', enName: 'Latvia' },
    { code: '370', mcc: '246', cnName: '立陶宛', enName: 'Lithuania' },
    { code: '373', mcc: '259', cnName: '摩尔多瓦', enName: 'Moldova' },
    { code: '389', mcc: '294', cnName: '北马其顿', enName: 'North Macedonia' },
    { code: '381', mcc: '220', cnName: '塞尔维亚', enName: 'Serbia' },
    { code: '421', mcc: '231', cnName: '斯洛伐克', enName: 'Slovakia' },
    { code: '386', mcc: '293', cnName: '斯洛文尼亚', enName: 'Slovenia' },
    { code: '380', mcc: '255', cnName: '乌克兰', enName: 'Ukraine' },
    { code: '43', mcc: '232', cnName: '奥地利', enName: 'Austria' },
    { code: '32', mcc: '206', cnName: '比利时', enName: 'Belgium' },
    { code: '45', mcc: '238', cnName: '丹麦', enName: 'Denmark' },
    { code: '358', mcc: '244', cnName: '芬兰', enName: 'Finland' },
    { code: '353', mcc: '272', cnName: '爱尔兰', enName: 'Ireland' },
    { code: '47', mcc: '242', cnName: '挪威', enName: 'Norway' },
    { code: '351', mcc: '268', cnName: '葡萄牙', enName: 'Portugal' },
    { code: '46', mcc: '240', cnName: '瑞典', enName: 'Sweden' },
    { code: '41', mcc: '228', cnName: '瑞士', enName: 'Switzerland' },
    { code: '591', mcc: '736', cnName: '玻利维亚', enName: 'Bolivia' },
    { code: '506', mcc: '712', cnName: '哥斯达黎加', enName: 'Costa Rica' },
    { code: '593', mcc: '740', cnName: '厄瓜多尔', enName: 'Ecuador' },
    { code: '503', mcc: '706', cnName: '萨尔瓦多', enName: 'El Salvador' },
    { code: '502', mcc: '704', cnName: '危地马拉', enName: 'Guatemala' },
    { code: '509', mcc: '372', cnName: '海地', enName: 'Haiti' },
    { code: '504', mcc: '708', cnName: '洪都拉斯', enName: 'Honduras' },
    { code: '505', mcc: '710', cnName: '尼加拉瓜', enName: 'Nicaragua' },
    { code: '507', mcc: '714', cnName: '巴拿马', enName: 'Panama' },
    { code: '595', mcc: '744', cnName: '巴拉圭', enName: 'Paraguay' },
    { code: '598', mcc: '748', cnName: '乌拉圭', enName: 'Uruguay' },
    { code: '58', mcc: '734', cnName: '委内瑞拉', enName: 'Venezuela' },
    { code: '973', mcc: '426', cnName: '巴林', enName: 'Bahrain' },
    { code: '964', mcc: '418', cnName: '伊拉克', enName: 'Iraq' },
    { code: '962', mcc: '416', cnName: '约旦', enName: 'Jordan' },
    { code: '965', mcc: '419', cnName: '科威特', enName: 'Kuwait' },
    { code: '961', mcc: '415', cnName: '黎巴嫩', enName: 'Lebanon' },
    { code: '968', mcc: '422', cnName: '阿曼', enName: 'Oman' },
    { code: '967', mcc: '421', cnName: '也门', enName: 'Yemen' }
] as const

/** 存在多个 MCC 时采用的代表运营商口径。 */
export const FINANCE_COUNTRY_PRIMARY_MCC_BASIS = {
    China: 'China Mobile：460',
    India: 'Reliance Jio：405',
    Japan: 'NTT DOCOMO：440',
    'United Arab Emirates': 'e& / Etisalat：424',
    'United Kingdom': 'VodafoneThree：234',
    'United States': 'Verizon Wireless：311'
} as const
